import Head from 'next/head'

import { DM_Sans } from 'next/font/google'
import styles from '@/styles/Home.module.css'
import Poster from "@/Components/poster/poster";
import TopRatedMovies from './movies/pages';
import { Suspense } from "react";
const dm_Sans = DM_Sans({ subsets: ['latin'] })

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={`${styles.main} ${dm_Sans.className}`}>
        <Poster />
        <TopRatedMovies />
      </main>
    </>
  );
}
